### ISSUE TITLE
Installation instruction [jax]

### ISSUE THREAD

**Issue by JulianKarlBauer** [nickelnine37/pykronecker#4]
Hi Ed,
if I try to install pykronecker with jax-support on ubuntu 22.04 following your instruction by
`pip3 install pykronecker[jax]`, I get

![image](https://user-images.githubusercontent.com/55383008/201353102-4612e013-e1c4-43b8-a023-029ab1e9eee3.png)

However, using `pip3 install "pykronecker[jax]"` works:

![image](https://user-images.githubusercontent.com/55383008/201353310-b0fe85b5-9934-494b-85e1-48cf873ecde5.png)

Would you mind fixing this in the installation instructions, or make it platform-specific, if required?

**Comment by JulianKarlBauer** [comment]
This is part of https://github.com/openjournals/joss-reviews/issues/4900#issue-1432670008

**Comment by nickelnine37** [comment]
Hi Julian, 

That's odd, I can't reproduce this problem on Ubuntu 22. Perhaps it's something to do with the zsh shell, as I am using bash.. Or maybe its a pip version issue? Quotation marks also work fine for me, so do you think I should just update the instructions to include quotation marks anyway, to cover all bases? 

Does 

```
python -m pip install pykronecker[jax]
```

work for you?

**Comment by JulianKarlBauer** [comment]
Hi Ed,

thanks for pointing this out. 
Your proposal does not change the result:
![image](https://user-images.githubusercontent.com/55383008/201366392-eeaf334a-1d59-4643-9961-4ccf20c9f87e.png)

However, if I switch from `zsh` to `bash`, your initial installation instruction works fine:
![image](https://user-images.githubusercontent.com/55383008/201366974-b764ad16-9fed-428d-9572-862abf2a7255.png)

From my perspective, the situation is as follows:
If `pip3 install "pykronecker[jax]"` works fine for Windows-user as well, I would recommend to us it and thereby include the small group of `zsh`-users.
If adding the extra apostrophes "" makes problems for any user group, e.g., Windows-user, then feel free to stick to your initial instruction.

**Comment by nickelnine37** [comment]
Thanks Julian. I've merged this in now https://github.com/nickelnine37/pykronecker/pull/5.

**Comment by JulianKarlBauer** [comment]
Thanks, this solves this issue.
